### ISSUE TITLE
Function to move an element(including paths) to an absolute position

### ISSUE THREAD

**Issue by slig** [DmitryBaranovskiy/raphael#171]
I tried to find an way to do that and found out a solution in this thread:
http://groups.google.com/group/raphaeljs/browse_thread/thread/f5dc3ea149d3540b

The problem is that the function needs an internal function "pathToRelative", so I believe that it isn't possible to make this function on a plugin. Hacking in the source code works, but I think that a function like this is useful enough to be included in the official distribution.

```
    Element[proto].moveTo = function(x, y){ 
            switch (this.type) { 
                    case "path": 
                            var path = pathToRelative(this.attrs.path), 
                                    dim = pathDimensions(path), 
                                    dx = (path[0][1] - dim.x) + x, 
                                    dy = (path[0][2] - dim.y) + y; 
                            path[0][1] = dx; 
                            path[0][2] = dy; 
                            return this.attr({path: path}); 
                            break; 
                    default: 
                            return this.attr({x: x, y: y}); 
                    break; 
            } 
            return this; 
    }; 
```

**Comment by theBull** [comment]
@DmitryBaranovskiy I've implemented a triangle by creating a closed path and have defined functionality to drag the triangle within the canvas. After calling `el.transform('...t100,60')` on a closed path, I want to "drop" the element by calling `el.transform('t0,0')` so that the element doesn't revert back to its original position on subsequent drags. This works for `rect`, `circle`, and `ellipse` but not for a closed `path`. I've noted that this line:

    elproto.transform = function (tstr) {
        var _ = this._;
        if (tstr == null) {
            return _.transform;
        }
        R._extractTransform(this, tstr);

        this.clip && $(this.clip, {transform: this.matrix.invert()});
        this.pattern && updatePosition(this);

        /* THIS LINE HERE */
        this.node && $(this.node, {transform: this.matrix});

        if (_.sx != 1 || _.sy != 1) {
            var sw = this.attrs[has]("stroke-width") ? this.attrs["stroke-width"] : 1;
            this.attr({"stroke-width": sw});
        }

        return this;
    };

...is the line that causes the call to `transform('t0,0')` to revert the path back to its original position, whereas the other elements stay in their dropped position.

Any chance this could be a bug?
