### ISSUE TITLE
Uncaught SyntaxError: Delete of an unqualified identifier in strict mode

### ISSUE THREAD

**Issue by lafama** [DmitryBaranovskiy/raphael#867]
```
R.ninja = function () {
        oldRaphael.was ? (g.win.Raphael = oldRaphael.is) : delete Raphael;
        return R;
    };
```
am getting the above Error after running Grunt uglify anyone know why

**Comment by ozdemirburak** [comment]
Same in here. I think it's something about delete, related to uglify.

**Comment by ptheofan** [comment]
same here with ngAnnotate. This is because we strict mode and under strict deleting a variable name is invalid. delete is meant to be used only with object properties 
i.e. 
`delete raphael.myProperty;` is valid. But `delete raphael;` is not.

I recommend removing the delete and just set it to undefined.

**Comment by markoshust** [comment]
Can this PR be merged in? Causing issues in Babel 6, program fails to build with same error.

**Comment by tomasAlabes** [comment]
Merged it to master myself. It's gonna be in the next version.
Thanks.
